pool:
  vmImage: 'Ubuntu 16.04'
steps:
- script: npm install
  workingDirectory: ~/source/.build
  displayName: 'Install NPM Packages'
- script: node .build/package.js
  workingDirectory: ~/source/
  displayName: 'Build Lab Content'
- script: zip -r cloud_and_enterprise_symbols-svg *
  workingDirectory: ~/source/Symbols
  displayName: 'Compress SVG Files'
- script: zip -r cloud_and_enterprise_symbols-png *
  workingDirectory: ~/source/tmp/png/Symbols
  displayName: 'Compress PNG Output Files'
- script: zip -r cloud_and_enterprise_symbols-jpg *
  workingDirectory: ~/source/tmp/jpg/Symbols
  displayName: 'Compress JPG Output Files'
