version: 2
jobs:
  build:
    docker:
      - image: circleci/node:stretch
    working_directory: ~/source
    steps:
      - checkout
      - run: sudo apt-get install zip unzip -y
      - run:
          working_directory: ~/source/.build
          name: Install NPM Packages
          command: npm install  
      - save_cache:
          key: dependency-cache-{{ checksum "~/source/.build/package.json" }}
          paths:
            - ~/source/.build/node_modules
      - run:
          working_directory: ~/source/
          name: Build Lab Content
          command: node .build/package.js
      - run:
          working_directory: ~/source/Symbols
          name: Compress SVG Files
          command: zip -r cloud_and_enterprise_symbols-svg *
      - store_artifacts:
          path: ~/source/Symbols/cloud_and_enterprise_symbols-svg.zip
          destination: cloud_and_enterprise_symbols-svg.zip
      - run:
          working_directory: ~/source/tmp/png/Symbols
          name: Compress PNG Output Files
          command: zip -r cloud_and_enterprise_symbols-png *
      - store_artifacts:
          path: ~/source/tmp/png/Symbols/cloud_and_enterprise_symbols-png.zip
          destination: cloud_and_enterprise_symbols-png.zip
      - run:
          working_directory: ~/source/tmp/jpg/Symbols
          name: Compress JPG Output Files
          command: zip -r cloud_and_enterprise_symbols-jpg *
      - store_artifacts:
          path: ~/source/tmp/png/Symbols/cloud_and_enterprise_symbols-jpg.zip
          destination: cloud_and_enterprise_symbols-jpg.zip
