version: 2
jobs:
  build:
    docker:
      - image: circleci/node:stretch
    working_directory: ~/source
    steps:
      - checkout
      - run: sudo apt-get install zip unzip -y
      - run:
          working_directory: ~/source/.build
          name: Install NPM Packages
          command: npm install  
      - save_cache:
          key: dependency-cache-{{ checksum "~/source/.build/package.json" }}
          paths:
            - ~/source/.build/node_modules
      - run:
          working_directory: ~/source/
          name: Build Lab Content
          command: node .build/package.js
      - run:
          working_directory: ~/source/tmp/png
          name: Compress PNG Output
          command: zip -r test *
      - store_artifacts:
          path: ~/source/tmp/png/test.zip
          destination: test.zip
